[project]
name = "example-plugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "msgpack==1.1.0",
]

[dependency-groups]
dev = [
    "pex>=2.33.7",
]
